# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  syntax-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get the CI tool
        uses: robinraju/release-downloader@v1
        with:
          repository: Ibot02/tmcr-newlogic-ci
          tag: "v1.0"
          filename: "tmcr-newlogic-ci"
          tarBall: false
          zipBall: false
      - name: Make it executable
        run: chmod +x "$GITHUB_WORKSPACE/tmcr-newlogic-ci"
      - name: Run the CI tool
        run: |
          cd $GITHUB_WORKSPACE
          ls
          if [[ -f tmcr-newlogic-ci ]]; then
            echo "exists"
          fi
          if [[ -x tmcr-newlogic-ci ]]; then
            ./tmcr-newlogic-ci *.logic
          fi
